export enum MessageType {
  GET_ACCOUNT = "GET_ACCOUNT",
  PONG_SEND_ACCOUNT = "PONG_SEND_ACCOUNT",
  GET_CHAIN = "GET_CHAIN", // TODO: not implemented
  RELOAD_COMMENTS = "RELOAD_COMMENTS", // TODO: not implemented
  SEND_MESSAGE = "SEND_MESSAGE",
  PONG_SEND_MESSAGE = "PONG_SEND_MESSAGE",
}
